# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-rRgQfRxCYvkXRlzrp1QzyGv1-XWKkO
"""

print("Pesquisa de Opinião - TudoWeb")
excelente = 0
bom = 0
ruim = 0
for i in range(50):
  print(f"\nEntrevistado {i+1}")
nome = input("Digite o nome: ")
idade = int(input("Digite a idade: "))
print("Opinião sobre o atendimento: ")
print("1 - EXCELENTE")
print("2 - BOM")
print("3 - RUIM")
opiniao = int(input("Escolha (1, 2 ou 3): "))
if opiniao == 1:
  excelente += 1
elif opiniao == 2:
  bom += 1
elif opiniao == 3:
  ruim += 1
else:
  print("Opção inválida!")
print("\n=== Resultado da Pesquisa ===")
print(f"Quantidade de respostas EXCELENTE: {excelente}")
print(f"Quantidade de respostas BOM: {bom}")
print(f"Quantidade de respostas RUIM: {ruim}")